@startuml

hide empty methods
hide empty fields
hide circle
hide stereotype



skinparam {
   !include_many color.txt
}
skinparam package {
   !include_many color.txt
}

skinparam node {
   !include_many color.txt
}

skinparam folder {
   !include_many color.txt
}

skinparam cloud {
   !include_many color.txt
}

skinparam database {
   !include_many color.txt
}

skinparam frame {
   '!include_many color.txt
   BackgroundColor White
}

skinparam rectangle {
   !include_many color.txt
}

frame domain1 <<domain1>>{
   rectangle domain1c1 <<domain1>><<domain3>>
   rectangle domain1c2 <<domain1>><<domain3>>
}

frame domain2 <<domain2>>{
   rectangle domain2c1 <<domain2>>
   rectangle domain2c2 <<domain2>><<domain3>>
}

frame domain3 <<domain3>>{
   rectangle domain3c1 <<domain3>>
}

frame CT <<domain1>><<domain2>><<domain3>>{
   database y <<domain1>><<domain2>><<domain3>>
}

y --> domain1c1 <<domain1>><<domain3>>
y --> domain2c1 <<domain2>>
y --> domain2c2 <<domain2>><<domain3>>

domain1c1 --> domain1c2 <<domain1>><<domain3>>
domain1c2 --> domain3c1 <<domain3>>

domain2c2 --> domain3c1 <<domain3>>

@enduml
